CREATE TABLE subscriptions
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255)                             NOT NULL,
    price       DOUBLE PRECISION                         NOT NULL,
    interval    SMALLINT                                 NOT NULL,
    status      SMALLINT,
    card_id     INTEGER                                  NOT NULL,
    CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);

ALTER TABLE bill_items
    ADD CONSTRAINT FK_BILL_ITEMS_ON_SUBSCRIPTION FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) ON DELETE CASCADE;

ALTER TABLE subscriptions
    ADD CONSTRAINT FK_SUBSCRIPTIONS_ON_CARD FOREIGN KEY (card_id) REFERENCES cards (id);