CREATE TABLE bills
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id   UUID                                     NOT NULL,
    start_date   date                                     NOT NULL,
    end_date     date                                     NOT NULL,
    due_date     date                                     NOT NULL,
    total_amount DOUBLE PRECISION                         NOT NULL,
    status       VARCHAR(255),
    CONSTRAINT pk_bills PRIMARY KEY (id)
);

ALTER TABLE bills
    ADD CONSTRAINT FK_BILLS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE;

ALTER TABLE transactions
    ALTER COLUMN installments SET NOT NULL;

ALTER TABLE accounts
    ADD payment_due_day INTEGER;

ALTER TABLE transactions
    ALTER COLUMN add_to_bill SET NOT NULL;

ALTER TABLE transactions
    ADD add_to_bill BOOLEAN;

ALTER TABLE transactions
    ADD installments INTEGER;

ALTER TABLE accounts
    ADD closing_day INTEGER;