CREATE TABLE bill_items
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bill_id            INTEGER                                  NOT NULL,
    transaction_id     INTEGER                                  NOT NULL,
    amount             DOUBLE PRECISION                         NOT NULL,
    installment_number INTEGER                                  NOT NULL,
    CONSTRAINT pk_bill_items PRIMARY KEY (id)
);

ALTER TABLE bill_items
    ADD CONSTRAINT FK_BILL_ITEMS_ON_BILL FOREIGN KEY (bill_id) REFERENCES bills (id) ON DELETE CASCADE;

ALTER TABLE bill_items
    ADD CONSTRAINT FK_BILL_ITEMS_ON_TRANSACTION FOREIGN KEY (transaction_id) REFERENCES transactions (id) ON DELETE CASCADE;