CREATE TABLE cards
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(255)                             NOT NULL,
    last_numbers VARCHAR(4)                               NOT NULL,
    card_limit   INTEGER                                  NOT NULL,
    type         SMALLINT                                 NOT NULL,
    account_id   INTEGER                                  NOT NULL,
    CONSTRAINT pk_cards PRIMARY KEY (id)
);

ALTER TABLE bills
    ADD CONSTRAINT FK_BILLS_ON_CARD FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE CASCADE;

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_CARD FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE CASCADE;